version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
        environment:
          POSTGRES_USER: postgres
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_DB: analytics_reporter_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: run tests
          command: npm test
      - run:
          name: deploy site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/deploy-ci.sh
            fi
