version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.19.1-browsers
        environment:
          POSTGRES_USER: postgres
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_DB: analytics_reporter_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: run tests
          command: npm test
      - run:
          name: install-cf-cli
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v    
      - run:
          name: deploy staging site
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              bin/deploy-staging-ci.sh
            fi
      - run:
          name: deploy production site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/deploy-production-ci.sh
            fi
