version: 2.1
jobs:
  common_steps:
    docker:
      - image: cimg/node:16.19.1-browsers
        environment:
          POSTGRES_USER: postgres
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_DB: analytics_reporter_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run tests
          command: npm test

  install_cf_cli:
    steps:
      - run:
          name: Install CF CLI
          command: |
              sudo curl -v -L -o cf8-cli-installer_8.7.4_x86-64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.4'
              sudo dpkg -i cf8-cli-installer_8.7.4_x86-64.deb

  develop_deploy:
    steps:
      - run:
          name: Install CF CLI
          command: |
              sudo curl -v -L -o cf8-cli-installer_8.7.4_x86-64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.4'
              sudo dpkg -i cf8-cli-installer_8.7.4_x86-64.deb
      - run:
          name: deploy
          command: |
              set -e
              # Log into cloud.gov
              cf api api.fr.cloud.gov
              cf login -u $CF_USERNAME_DEV -p $CF_PASSWORD_DEV -o gsa-opp-analytics -s analytics-dev
              cf push analytics-reporter-develop --strategy rolling
              cf logout

  staging_deploy:
    steps:
      - run:
          name: Install CF CLI
          command: |
              sudo curl -v -L -o cf8-cli-installer_8.7.4_x86-64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.4'
              sudo dpkg -i cf8-cli-installer_8.7.4_x86-64.deb
      - run:
          name: Install CF CLI
          command: |
              sudo curl -v -L -o cf8-cli-installer_8.7.4_x86-64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.4'
              sudo dpkg -i cf8-cli-installer_8.7.4_x86-64.deb

      - run:
          name: deploy
          command: |
              set -e
              cf login -a api.fr.cloud.gov -u $CF_STAGING_SPACE_DEPLOYER_USERNAME -p $CF_STAGING_SPACE_DEPLOYER_PASSWORD -o gsa-opp-analytics -s analytics-staging
              cf push analytics-reporter-staging --strategy rolling
              cf logout


  production_deploy:
    steps:
      - run:
          name: Install CF CLI
          command: |
              sudo curl -v -L -o cf8-cli-installer_8.7.4_x86-64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.4'
              sudo dpkg -i cf8-cli-installer_8.7.4_x86-64.deb
      - run:
          name: Install CF CLI
          command: |
              sudo curl -v -L -o cf8-cli-installer_8.7.4_x86-64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.4'
              sudo dpkg -i cf8-cli-installer_8.7.4_x86-64.deb

      - run:
          name: deploy
          command: |
              set -e
              cf login -a api.fr.cloud.gov -u $CF_PRODUCTION_SPACE_DEPLOYER_USERNAME -p $CF_PRODUCTION_SPACE_DEPLOYER_PASSWORD -o gsa-opp-analytics -s analytics-prod
              cf push analytics-reporter-production --strategy rolling
              cf logout

workflows:
  version: 2
  build:
    jobs:
      - common_steps
      - develop_deploy:
          filters:
            branches:
              only:
                - develop
      - staging_deploy:
          filters:
            branches:
              only:
                - stage
      - production_deploy:
          filters:
            branches:
              only:
                - master
